branch-defaults:
  default:
    environment: refugee-prod
    group_suffix: null
  master:
    environment: Sample-env
    group_suffix: null
global:
  application_name: wearemakers
  default_ec2_keyname: aws-eb-refugee
  default_platform: Node.js
  default_region: us-west-2
  profile: wearemakers
  sc: git
