branch-defaults:
  default:
    environment: refugee-prod
    group_suffix: null
  master:
    environment: refugee-prod
global:
  application_name: refugee
  default_ec2_keyname: aws-eb
  default_platform: Node.js
  default_region: us-west-2
  profile: refugee
  sc: null
